-- Menu table schema for enrichment
-- This table stores menu items that need to be enriched with AI

CREATE TABLE IF NOT EXISTS public.menu (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Dish Name" TEXT NOT NULL,
    ingredients TEXT,
    description TEXT,
    vegetarian BOOLEAN,
    non_vegetarian BOOLEAN,
    enrichment_status TEXT DEFAULT 'pending' CHECK (enrichment_status IN ('pending', 'completed', 'failed')),
    enrichment_updated_at TIMESTAMP WITH TIME ZONE,
    -- Enrichment fields
    ingredients_complete TEXT,
    vegetarian_flag BOOLEAN,
    vegan_flag BOOLEAN,
    non_vegetarian_flag BOOLEAN,
    -- Similar dishes
    similar_mexican_dish_1 TEXT,
    similar_mexican_similarity_1 INTEGER,
    similar_mexican_dish_2 TEXT,
    similar_mexican_similarity_2 INTEGER,
    similar_european_dish_1 TEXT,
    similar_european_similarity_1 INTEGER,
    similar_european_dish_2 TEXT,
    similar_european_similarity_2 INTEGER,
    similar_south_american_dish_1 TEXT,
    similar_south_american_similarity_1 INTEGER,
    similar_south_american_dish_2 TEXT,
    similar_south_american_similarity_2 INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_menu_dish_name ON public.menu("Dish Name");
CREATE INDEX IF NOT EXISTS idx_menu_enrichment_status ON public.menu(enrichment_status);

-- Enable RLS
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Anyone can view menu items" ON public.menu FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert menu items" ON public.menu FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update menu items" ON public.menu FOR UPDATE USING (auth.role() = 'authenticated');

-- Grant permissions
GRANT SELECT ON public.menu TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.menu TO authenticated;

-- Insert sample menu data for enrichment
INSERT INTO public.menu ("Dish Name", ingredients, description) VALUES
('Grilled Chicken', 'chicken, herbs, spices', 'Tender grilled chicken with herbs'),
('Caesar Salad', 'lettuce, croutons, parmesan, caesar dressing', 'Fresh romaine lettuce with Caesar dressing'),
('Pasta Carbonara', 'pasta, bacon, eggs, cheese, cream', 'Creamy pasta with bacon and eggs'),
('Fish Tacos', 'fish, tortillas, cabbage, lime', 'Fresh fish tacos with cabbage slaw'),
('Vegetable Stir Fry', 'broccoli, carrots, bell peppers, soy sauce', 'Mixed vegetables stir fried'),
('Beef Burger', 'beef, bun, lettuce, tomato, cheese', 'Classic beef burger'),
('Margherita Pizza', 'dough, tomato sauce, mozzarella, basil', 'Classic pizza with tomato and basil'),
('Chicken Curry', 'chicken, curry spices, coconut milk, rice', 'Spicy chicken curry'),
('Greek Salad', 'tomatoes, cucumbers, feta, olives, olive oil', 'Traditional Greek salad'),
('Pad Thai', 'rice noodles, shrimp, tofu, peanuts, bean sprouts', 'Thai stir fried noodles'),
('Sushi Rolls', 'rice, seaweed, fish, vegetables', 'Assorted sushi rolls'),
('Chocolate Cake', 'flour, sugar, chocolate, eggs, butter', 'Rich chocolate cake'),
('French Fries', 'potatoes, oil, salt', 'Crispy fried potatoes'),
('Ice Cream', 'cream, sugar, vanilla', 'Vanilla ice cream'),
('Coffee', 'coffee beans, water', 'Fresh brewed coffee'),
('Green Tea', 'green tea leaves, hot water', 'Traditional green tea'),
('Orange Juice', 'oranges', 'Fresh squeezed orange juice'),
('Mineral Water', 'water', 'Sparkling mineral water'),
('Club Sandwich', 'bread, chicken, bacon, lettuce, tomato, mayo', 'Triple decker sandwich'),
('Mushroom Risotto', 'rice, mushrooms, parmesan, white wine, broth', 'Creamy mushroom risotto'),
('Lamb Kebabs', 'lamb, onions, peppers, spices', 'Grilled lamb skewers'),
('Falafel Wrap', 'falafel, pita, lettuce, tomato, tahini', 'Middle Eastern falafel wrap'),
('Tiramisu', 'mascarpone, coffee, ladyfingers, cocoa', 'Classic Italian dessert'),
('Spring Rolls', 'rice paper, vegetables, shrimp, dipping sauce', 'Fresh spring rolls'),
('Beef Stroganoff', 'beef, mushrooms, sour cream, noodles', 'Russian beef stroganoff'),
('Quinoa Bowl', 'quinoa, vegetables, avocado, dressing', 'Healthy quinoa bowl'),
('Shakshuka', 'eggs, tomatoes, peppers, spices', 'Middle Eastern eggs in tomato sauce'),
('Pho', 'rice noodles, beef, broth, herbs', 'Vietnamese noodle soup'),
('Dim Sum', 'dumplings, buns, various fillings', 'Assorted Chinese dumplings'),
('Paella', 'rice, seafood, chicken, saffron, vegetables', 'Spanish seafood rice dish'),
('Ratatouille', 'eggplant, zucchini, tomatoes, herbs', 'French vegetable stew'),
('Kimchi Fried Rice', 'rice, kimchi, vegetables, gochujang', 'Spicy Korean fried rice'),
('Butter Chicken', 'chicken, butter, cream, spices, naan', 'Creamy Indian curry'),
('Ceviche', 'fish, lime, onions, cilantro, chili', 'Peruvian marinated fish'),
('Empanadas', 'dough, meat or cheese filling, spices', 'South American pastries'),
('Feijoada', 'black beans, pork, sausage, rice', 'Brazilian bean stew'),
('Arepas', 'cornmeal, cheese or meat filling', 'Colombian corn cakes'),
('Chimichurri Steak', 'beef, chimichurri sauce, vegetables', 'Argentinian steak'),
('Lomo Saltado', 'beef, onions, tomatoes, fries, soy sauce', 'Peruvian stir fry'),
('Asado', 'various grilled meats, chimichurri', 'Argentinian barbecue'),
('Moqueca', 'fish, coconut milk, palm oil, rice', 'Brazilian fish stew'),
('Churrasco', 'skirt steak, chimichurri, yuca', 'Uruguayan steak'),
('Pastel de Choclo', 'corn, ground beef, onions, olives', 'Chilean corn pie'),
('Humita', 'corn, cheese, spices', 'Andean corn dish'),
('Sancocho', 'meat, plantains, yuca, corn', 'Colombian stew'),
('Ajiaco', 'chicken, potatoes, corn, cream', 'Colombian chicken soup'),
('Ropa Vieja', 'shredded beef, peppers, onions, spices', 'Cuban shredded beef'),
('Picadillo', 'ground beef, olives, raisins, spices', 'Latin American ground beef'),
('Tamales', 'corn dough, meat filling, wrapped in leaves', 'Central American steamed cakes'),
('Anafre', 'cheese, spices, wrapped in leaves', 'Colombian cheese dish'),
('Bandeja Paisa', 'rice, beans, meat, plantains, avocado', 'Colombian national dish'),
('Arequipe', 'milk, sugar, vanilla', 'Colombian caramel sauce'),
('Tres Leches Cake', 'sponge cake, three milks, cream', 'Latin American cake'),
('Flan', 'eggs, milk, sugar, caramel', 'Spanish custard'),
('Churros', 'dough, oil, cinnamon sugar', 'Spanish fried dough'),
('Crema Catalana', 'milk, eggs, sugar, cinnamon', 'Spanish crème brûlée'),
('Gazpacho', 'tomatoes, peppers, garlic, bread, olive oil', 'Spanish cold soup'),
('Patatas Bravas', 'potatoes, spicy tomato sauce', 'Spanish spicy potatoes'),
('Jamón Ibérico', 'iberico ham, bread', 'Spanish cured ham'),
('Tortilla Española', 'potatoes, eggs, onions', 'Spanish omelette'),
('Paella Valenciana', 'rice, chicken, rabbit, vegetables, saffron', 'Valencian paella'),
('Fabada Asturiana', 'beans, chorizo, morcilla, pork', 'Asturian bean stew'),
('Cocido Madrileño', 'chickpeas, meats, vegetables', 'Madrid chickpea stew'),
('Calçots', 'spring onions, romesco sauce', 'Catalan grilled onions'),
('Escudella', 'meat, vegetables, pasta', 'Catalan stew'),
('Sarsuela', 'seafood, tomato sauce, rice', 'Catalan seafood stew'),
('Fideuà', 'noodles, seafood, broth', 'Catalan noodle paella'),
('Arròs Negre', 'rice, squid ink, seafood', 'Catalan black rice'),
('Suquet de Peix', 'fish, potatoes, garlic, almonds', 'Catalan fish stew'),
('Olla Aranesa', 'meat, vegetables, chickpeas', 'Catalan mountain stew'),
('Escargots', 'snails, garlic butter, parsley', 'French snails'),
('Bouillabaisse', 'fish, shellfish, vegetables, saffron', 'French fish stew'),
('Ratatouille', 'eggplant, zucchini, tomatoes, herbs', 'French vegetable stew'),
('Coq au Vin', 'chicken, wine, mushrooms, onions', 'French chicken in wine'),
('Boeuf Bourguignon', 'beef, wine, mushrooms, onions', 'French beef stew'),
('Cassoulet', 'beans, duck, sausage, pork', 'French bean casserole'),
('Confit de Canard', 'duck, fat, potatoes', 'French duck confit'),
('Foie Gras', 'duck liver, toast', 'French foie gras'),
('Salade Niçoise', 'tuna, olives, potatoes, eggs, beans', 'French Niçoise salad'),
('Quiche Lorraine', 'pastry, bacon, eggs, cream', 'French bacon quiche'),
('Tarte Tatin', 'apples, pastry, caramel', 'French apple tart'),
('Crème Brûlée', 'cream, eggs, sugar, vanilla', 'French crème brûlée'),
('Profiteroles', 'choux pastry, ice cream, chocolate', 'French cream puffs'),
('Madeleines', 'butter, sugar, eggs, flour, lemon', 'French shell cakes'),
('Macarons', 'almond flour, sugar, egg whites', 'French macarons'),
('Soufflé', 'eggs, flour, milk, flavoring', 'French soufflé'),
('Blanquette de Veau', 'veal, cream, mushrooms, rice', 'French veal stew'),
('Navarin d''Agneau', 'lamb, vegetables, herbs', 'French lamb stew'),
('Daube Provençale', 'beef, wine, olives, herbs', 'French beef daube'),
('Choucroute', 'sauerkraut, sausages, pork, potatoes', 'Alsatian sauerkraut'),
('Tartiflette', 'potatoes, reblochon cheese, bacon', 'French potato dish'),
('Raclette', 'melted cheese, potatoes, meats', 'Swiss/French cheese dish'),
('Fondue', 'melted cheese, bread, wine', 'Swiss cheese fondue'),
('Rösti', 'potatoes, butter, onions', 'Swiss potato dish'),
('Zürcher Geschnetzeltes', 'veal, cream, mushrooms, rice', 'Swiss veal stew'),
('Spätzle', 'egg noodles, butter', 'German egg noodles'),
('Schnitzel', 'breaded meat, potatoes, salad', 'German/Austrian breaded cutlet'),
('Bratwurst', 'sausages, mustard, bread', 'German sausages'),
('Sauerkraut', 'cabbage, caraway, pork', 'German sauerkraut'),
('Eisbein', 'pork knuckle, sauerkraut', 'German pork dish'),
('Königsberger Klopse', 'meatballs, capers, cream', 'German meatballs'),
('Labskaus', 'corned beef, potatoes, beetroot', 'German sailor''s dish'),
('Maultaschen', 'pasta, meat filling, broth', 'German meat dumplings'),
('Schwarzwälder Kirschtorte', 'chocolate, cherries, cream', 'German Black Forest cake'),
('Apfelstrudel', 'pastry, apples, cinnamon, raisins', 'Austrian apple strudel'),
('Kaiserschmarrn', 'pancakes, raisins, powdered sugar', 'Austrian shredded pancakes'),
('Sachertorte', 'chocolate cake, apricot jam', 'Austrian chocolate cake'),
('Palatschinken', 'crepes, fillings, chocolate', 'Austrian crepes'),
('Goulash', 'beef, paprika, onions, dumplings', 'Hungarian goulash'),
('Paprika Chicken', 'chicken, paprika, sour cream', 'Hungarian paprika chicken'),
('Lángos', 'fried dough, toppings', 'Hungarian fried bread'),
('Halászlé', 'fish soup, paprika, onions', 'Hungarian fish soup'),
('Töltött Káposzta', 'cabbage, meat filling, sour cream', 'Hungarian stuffed cabbage'),
('Pörkölt', 'meat, paprika, onions', 'Hungarian meat stew'),
('Tokaji', 'wine, grapes', 'Hungarian sweet wine'),
('Dobos Torta', 'sponge cake, chocolate buttercream', 'Hungarian layer cake'),
('Kürtőskalács', 'pastry, sugar, nuts', 'Hungarian chimney cake'),
('Túrós Csusza', 'noodles, cottage cheese, sour cream', 'Hungarian cheese noodles'),
('Hortobágyi Palacsinta', 'crepes, meat filling, paprika', 'Hungarian meat crepes'),
('Jókai Bableves', 'bean soup, vegetables, sausage', 'Hungarian bean soup'),
('Székelykáposzta', 'sauerkraut, pork, sour cream', 'Hungarian sauerkraut with pork'),
('Somlói Galuska', 'sponge cake, chocolate, walnuts', 'Hungarian trifle'),
('Rákóczi Túró', 'cottage cheese, raisins, cinnamon', 'Hungarian cheese dessert'),
('Mákos Tészta', 'noodles, poppy seeds, sugar', 'Hungarian poppy seed noodles'),
('Aranygaluska', 'dumplings, vanilla sauce', 'Hungarian golden dumplings'),
('Gundel Palacsinta', 'crepes, walnut filling, chocolate', 'Hungarian walnut crepes'),
('Zserbó Szelet', 'pastry, apricot jam, walnuts', 'Hungarian layered cake'),
('Krémes', 'pastry cream, puff pastry', 'Hungarian cream slice'),
('Tiramisu', 'mascarpone, coffee, ladyfingers', 'Italian tiramisu'),
('Risotto alla Milanese', 'rice, saffron, parmesan, wine', 'Italian saffron risotto'),
('Osso Buco', 'veal shanks, vegetables, wine', 'Italian veal shanks'),
('Saltimbocca', 'veal, prosciutto, sage, wine', 'Italian veal with ham'),
('Panna Cotta', 'cream, sugar, gelatin, berries', 'Italian cream dessert'),
('Gelato', 'milk, sugar, flavorings', 'Italian ice cream'),
('Cannoli', 'pastry shells, ricotta filling', 'Sicilian cannoli'),
('Arancini', 'rice balls, meat sauce, mozzarella', 'Sicilian rice balls'),
('Caprese Salad', 'tomatoes, mozzarella, basil, olive oil', 'Italian tomato salad'),
('Bruschetta', 'bread, tomatoes, garlic, basil', 'Italian toasted bread'),
('Focaccia', 'bread, olive oil, herbs, salt', 'Italian flatbread'),
('Pesto Genovese', 'basil, pine nuts, garlic, olive oil', 'Italian basil sauce'),
('Ossobuco alla Milanese', 'veal shanks, vegetables, gremolata', 'Milanese veal shanks'),
('Risotto ai Funghi', 'rice, mushrooms, parmesan, wine', 'Italian mushroom risotto'),
('Polenta', 'cornmeal, butter, parmesan', 'Italian cornmeal dish'),
('Bagna Cauda', 'garlic, anchovies, olive oil, vegetables', 'Italian dipping sauce'),
('Vitello Tonnato', 'veal, tuna sauce, capers', 'Italian veal with tuna'),
('Scaloppine al Limone', 'veal, lemon, white wine', 'Italian lemon veal'),
('Melanzane alla Parmigiana', 'eggplant, tomato sauce, mozzarella', 'Italian eggplant parmesan'),
('Pasta alla Norma', 'pasta, eggplant, tomato sauce, ricotta', 'Sicilian pasta'),
('Spaghetti alle Vongole', 'spaghetti, clams, garlic, white wine', 'Italian clam pasta'),
('Linguine alle Cozze', 'linguine, mussels, garlic, white wine', 'Italian mussel pasta'),
('Fettuccine Alfredo', 'fettuccine, butter, parmesan, cream', 'Italian cream pasta'),
('Penne all''Arrabbiata', 'penne, tomato sauce, chili, garlic', 'Italian spicy pasta'),
('Lasagna', 'pasta sheets, meat sauce, béchamel, mozzarella', 'Italian layered pasta'),
('Ravioli', 'pasta, fillings, sauce', 'Italian stuffed pasta'),
('Tortellini', 'small pasta, meat filling, broth', 'Italian meat dumplings'),
('Tagliatelle al Ragù', 'tagliatelle, meat sauce', 'Italian meat pasta'),
('Pappardelle al Cinghiale', 'pappardelle, wild boar sauce', 'Italian wild boar pasta'),
('Gnocchi', 'potato dumplings, sauce', 'Italian potato dumplings'),
('Risotto alla Pescatora', 'rice, seafood, wine, tomatoes', 'Italian seafood risotto'),
('Zuppa di Pesce', 'fish soup, seafood, tomatoes', 'Italian fish soup'),
('Baccalà alla Vicentina', 'salt cod, milk, onions, polenta', 'Italian salt cod'),
('Sarde a Beccafico', 'sardines, breadcrumbs, pine nuts, raisins', 'Sicilian stuffed sardines'),
('Caponata', 'eggplant, celery, tomatoes, olives, capers', 'Sicilian vegetable dish'),
('Pasta con le Sarde', 'pasta, sardines, fennel, pine nuts', 'Sicilian pasta with sardines'),
('Sfincione', 'thick pizza, tomato sauce, onions, anchovies', 'Sicilian pizza'),
('Granita', 'ice, sugar, flavorings', 'Sicilian ice'),
('Cassata Siciliana', 'sponge cake, ricotta, marzipan, chocolate', 'Sicilian cake'),
('Cannoli Siciliani', 'pastry tubes, ricotta filling, chocolate', 'Sicilian cannoli'),
('Pistachio Gelato', 'pistachios, milk, sugar', 'Sicilian pistachio ice cream'),
('Seadas', 'fried pastry, cheese, honey', 'Sardinian cheese pastries'),
('Culurgiones', 'pasta, potato filling, mint', 'Sardinian potato dumplings'),
('Malloreddus', 'semolina pasta, saffron, sausage', 'Sardinian pasta'),
('Pane Carasau', 'thin bread, olive oil, salt', 'Sardinian flatbread'),
('Zuppa Gallurese', 'bread, meat broth, cheese', 'Sardinian bread soup'),
('Porceddu', 'suckling pig, myrtle, herbs', 'Sardinian roast pig'),
('Bottarga', 'mullet roe, pasta, olive oil', 'Sardinian fish roe'),
('Vermentino', 'white wine, seafood', 'Sardinian white wine'),
('Mirto', 'myrtle liqueur, herbs', 'Sardinian liqueur'),
('Amaretti', 'almond cookies, sugar', 'Italian almond cookies'),
('Biscotti', 'almond cookies, anise', 'Italian twice-baked cookies'),
('Pizzelle', 'waffle cookies, anise', 'Italian waffle cookies'),
('Baicoli', 'sweet biscuits, butter', 'Venetian biscuits'),
('Bussolà', 'ring-shaped cookies, sugar', 'Venetian cookies'),
('Croccante', 'almond brittle, sugar', 'Italian almond brittle'),
('Mostaccioli', 'spicy cookies, chocolate', 'Italian spiced cookies'),
('Sbrisolona', 'crumbly cake, almonds', 'Italian almond cake'),
('Castagnaccio', 'chestnut flour, pine nuts, rosemary', 'Italian chestnut cake'),
('Panforte', 'nuts, fruits, honey, spices', 'Sienese spice cake'),
('Ricciarelli', 'almond cookies, sugar, cinnamon', 'Sienese almond cookies'),
('Cavallucci', 'almond cookies, anise, coriander', 'Sienese spice cookies'),
('Cenci', 'fried pastry, powdered sugar', 'Italian fried dough'),
('Zeppole', 'fried dough, powdered sugar', 'Italian fried doughnuts'),
('Sfogliatelle', 'pastry, ricotta filling, cinnamon', 'Neapolitan lobster tails'),
('Babà', 'yeast cake, rum syrup', 'Neapolitan rum cake'),
('Pastiera', 'pastry, ricotta,